pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Pre-Deliver') {
            steps {
                echo("Pre-delivery")
            }
        }
        stage('Deliver') {
            steps {
                echo('./jenkins/scripts/deliver.sh')
            }
        }
    }
}
